'use strict';
const app=document.body.dataset.app;
const names={maths:'Maths Quest',spelling:'Spellbound',words:'Capy Word Builder'};
const topics=app==='maths'?MathsTopics:[...SpellingTopics,{id:'words',title:'Word discovery',icon:'✦',desc:'Find words with Capy and follow your curiosity.',code:'Spelling and vocabulary enrichment'}];
const main=document.querySelector('main');
const key='learning-preview-v1-'+app;
let saveAvailable=true,state={sessions:0,days:[],skills:{},words:{},stars:0,theme:'River',story:''};
try{let saved=JSON.parse(localStorage.getItem(key));if(saved&&typeof saved==='object'){state={...state,...saved};if(!Array.isArray(state.days))state.days=[];if(!state.skills||typeof state.skills!=='object')state.skills={};if(!state.words||typeof state.words!=='object')state.words={}}}catch{saveAvailable=false}
// Saved browser data can be incomplete after an interrupted write or older release.
const safeCount=value=>Number.isFinite(value)&&value>=0?Math.floor(value):0;
state.sessions=safeCount(state.sessions);state.stars=safeCount(state.stars);
state.days=[...new Set(state.days.filter(d=>typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)))];
state.story=typeof state.story==='string'?state.story:'';
state.theme=['River','Ocean','Sunset','Forest'].includes(state.theme)?state.theme:'River';
state.skills=Object.fromEntries(Object.entries(state.skills).filter(([,v])=>v&&typeof v==='object').map(([id,v])=>[id,{independent:safeCount(v.independent),supported:safeCount(v.supported),completed:safeCount(v.completed)}]));
state.words=Object.fromEntries(Object.entries(state.words).filter(([,v])=>v&&typeof v.word==='string'&&Number.isFinite(v.due)).map(([id,v])=>[id,{...v,successes:safeCount(v.successes)}]));

function save(){try{localStorage.setItem(key,JSON.stringify(state))}catch{saveAvailable=false}}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function day(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function streak(){let n=0,d=new Date();if(!state.days.includes(day(d)))d.setDate(d.getDate()-1);while(state.days.includes(day(d))){n++;d.setDate(d.getDate()-1)}return n}
function complete(){state.sessions++;state.stars+=5;const today=day();if(!state.days.includes(today))state.days.push(today);save()}
function view(html,tab='play'){if('speechSynthesis' in window)window.speechSynthesis.cancel();main.innerHTML=html;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===tab));window.scrollTo(0,0);main.focus({preventScroll:true})}
function notice(){return `<p class="notice">${saveAvailable?'Progress is saved on this device and browser.':'Saving is unavailable in this browser. You can still practise, but progress may not be kept.'}</p>`}
function home(){if(app==='words'){wordHome();return}view(`<section class="hero"><div class="welcome"><span class="eyebrow">Year 4 · Your next adventure</span><h1>${app==='maths'?'Big ideas. Small steps.':'Make words your own.'}</h1><p class="muted">${app==='maths'?'Choose something to explore. Build an idea, try it out, and get a little more confident.':'Listen closely, explore word parts and put your ideas into words.'}</p></div><aside class="today"><span class="eyebrow">Your practice streak</span><p><strong>${streak()} ${streak()===1?'day':'days'}</strong></p><span>${state.days.includes(day())?'Today’s practice is complete. Nice work.':'One short session is enough for today.'}</span></aside></section><div class="section-title"><h2>Choose your journey</h2><span class="pill">No timer · Help anytime</span></div><div class="grid">${topics.map(t=>`<button class="card" data-topic="${t.id}"><span class="symbol">${t.icon}</span><h3>${t.title}</h3><p>${t.desc}</p><div class="foot"><span>${state.skills[t.id]?.completed?state.skills[t.id].completed+' sessions explored':'Start exploring'}</span><span>Start →</span></div></button>`).join('')}</div>${notice()}<p><a href="classic.html">Open the original challenge game</a></p>`);main.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>start(b.dataset.topic))}
let session=null;
function start(id){dailyActive=false;if(id==='words'){wordHome();return}if(id==='writing'){writing();return}let t=topics.find(t=>t.id===id),deck;if(app==='maths')deck=Array.from({length:6},(_,i)=>({...makeMath(id,i),id:id+':'+i,topic:id}));else if(SpellWords[id]){let entries=shuffle(SpellWords[id]);entries.sort((a,b)=>{const pa=state.words[id+':'+a[0]],pb=state.words[id+':'+b[0]];return (pa?pa.due:0)-(pb?pb.due:0)});deck=entries.slice(0,6).map(e=>spellQuestion(id,e))}else deck=shuffle(EnglishQuestions[id]).map((q,i)=>({...q,id:id+':'+i,topic:id}));session={topic:t,deck,index:0,independent:0,supported:0,helped:false,finished:false};question()}
function question(){const s=session;if(s.index>=s.deck.length){finish();return}s.helped=false;s.finished=false;s.currentRecorded=false;const item=s.deck[s.index];view(`<section class="session"><div class="session-head"><button class="btn quiet" id="exit">Save & leave</button><span class="pill">${s.topic.title}</span><span>${s.index+1} / ${s.deck.length}</span></div><div class="progress" role="progressbar" aria-label="Session progress" aria-valuenow="${s.index}" aria-valuemin="0" aria-valuemax="${s.deck.length}"><span style="width:${s.index/s.deck.length*100}%"></span></div><article class="question"><span class="eyebrow">${item.review?'Try it again · From memory':'Take your time'}</span><h1>${esc(item.prompt)}</h1>${item.visual?`<div class="visual">${item.visual}</div>`:''}${item.kind==='spell'?`<button class="btn secondary" id="hear">Hear word & sentence</button><p class="muted">${esc(item.sentence.replace(new RegExp(item.word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'),'_____'))}</p><form id="spell-form"><label for="spelling" class="sr-only">Your spelling</label><input class="field" id="spelling" autocomplete="off" autocapitalize="none" spellcheck="false" placeholder="Type the word" aria-describedby="feedback"><button class="btn" type="submit">Check spelling</button></form><div id="study"></div>`:`<div class="answers">${item.choices.map((c,i)=>`<button class="answer" data-choice="${i}">${esc(c)}</button>`).join('')}</div>`}<div id="feedback" class="feedback" role="status" aria-live="polite"></div><div class="row"><button class="btn secondary" id="hint">Help me start</button><button class="btn quiet" id="explain">Show me how</button><button class="btn" id="next" hidden>Continue</button></div></article><p class="caption">Hints are part of learning. Your progress stays safe.</p></section>`);document.getElementById('exit').onclick=()=>{save();home()};document.getElementById('hint').onclick=()=>{s.helped=true;feedback(item.hint,'help')};document.getElementById('explain').onclick=()=>{s.helped=true;if(item.kind==='spell'){studyWord(item)}else feedback(item.explain,'help')};document.getElementById('next').onclick=()=>{s.index++;question()};if(item.kind==='spell'){document.getElementById('hear').onclick=()=>speak(item.word+'. '+item.sentence);document.getElementById('spell-form').onsubmit=e=>{e.preventDefault();const input=document.getElementById('spelling');if(input.value.trim())answer(input.value.trim().toLowerCase().replaceAll('’',"'"))};}else main.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>answer(item.choices[Number(b.dataset.choice)],b))}
function feedback(message,type=''){const f=document.getElementById('feedback');f.textContent=message;f.className='feedback '+type}
function studyWord(item){let label=session.topic.id==='parts'?'Word parts that have a meaning':session.topic.id==='longer'?'Chunks to help you practise':session.topic.id==='homophones'?'Check the meaning and spelling':'Spellings for the sounds';document.getElementById('study').innerHTML=`<p class="muted">${label}</p><div class="sound-parts">${item.parts.map(p=>`<span>${esc(p)}</span>`).join('')}</div><p><strong>${esc(item.word)}</strong> — ${esc(item.sentence)}</p><button class="btn secondary" id="hide-study">Cover & try</button>`;document.getElementById('spelling').value='';document.getElementById('hide-study').onclick=()=>{document.getElementById('study').innerHTML='';document.getElementById('spelling').focus()};feedback(item.hint,'help')}
function answer(value,button){const s=session,item=s.deck[s.index];if(s.finished)return;if(value!==item.answer){s.helped=true;if(button){button.classList.add('wrong');button.disabled=true}feedback('Not quite yet. '+item.hint,'warn');if(item.kind==='spell'){let attempt=document.getElementById('spelling').value;let n=0;while(n<attempt.length&&attempt[n].toLowerCase()===item.word[n])n++;feedback((n?`Your first ${n} ${n===1?'letter is':'letters are'} in place. `:'')+'Say the word again. Use “Show me how” to study the spelling, then cover it and retry.','warn')}return}s.finished=true;if(button)button.classList.add('correct');main.querySelectorAll('.answer').forEach(b=>b.disabled=true);if(item.kind==='spell'){document.getElementById('spelling').disabled=true;document.querySelector('#spell-form button').disabled=true;document.getElementById('study').innerHTML=''}feedback((s.helped?'You worked it out with help. ':'You did it on your own! ')+item.explain);record(item,!s.helped);if(s.helped&&!item.review){s.supported++;s.deck.push({...item,review:true})}else if(s.helped)s.supported++;else s.independent++;document.getElementById('hint').hidden=true;document.getElementById('explain').hidden=true;document.getElementById('next').hidden=false;document.getElementById('next').focus()}
function record(item,independent){let t=state.skills[item.topic]||(state.skills[item.topic]={independent:0,supported:0,completed:0});t[independent?'independent':'supported']++;if(item.kind==='spell'){let prev=state.words[item.id]||{successes:0};let successes=independent?prev.successes+1:0;state.words[item.id]={word:item.word,successes,due:Date.now()+(independent?Math.min(14,2**successes):1)*86400000,last:day()}}save()}
function finish(){complete();const t=state.skills[session.topic.id]||(state.skills[session.topic.id]={independent:0,supported:0,completed:0});t.completed++;save();view(`<section class="session"><span class="eyebrow">Session complete</span><h1>A little further than before.</h1><p class="muted">You explored ${esc(session.topic.title.toLowerCase())}. Come back another day to see what you remember.</p><div class="stats"><div class="stat"><strong>${session.independent}</strong><span>Answers on my own</span></div><div class="stat"><strong>${session.supported}</strong><span>Answers with help</span></div><div class="stat"><strong>+5</strong><span>Stars for practising</span></div></div><div class="reward"><h2>${streak()}-day practice streak</h2><p>Today counts. Trying, using hints and correcting mistakes all belong here.</p></div><div class="row"><button class="btn" id="home">Choose another journey</button><button class="btn secondary" id="collection">My collection</button></div></section>`);document.getElementById('home').onclick=home;document.getElementById('collection').onclick=collection}
function speak(text){if(!('speechSynthesis'in window)){feedback('Audio is unavailable here. Use “Show me how” to study the word, then cover it and practise.','warn');return}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='en-AU';utterance.rate=.85;utterance.onerror=()=>{if(document.getElementById('feedback'))feedback('Audio could not play. Use “Show me how”, then cover and try.','warn')};window.speechSynthesis.speak(utterance)}
function progress(){let independent=Object.entries(state.skills).filter(([id])=>id!=='words').reduce((n,[,t])=>n+(t.independent||0),0);view(`<span class="eyebrow">My progress</span><h1>Look what you’ve done!</h1><div class="stats"><div class="stat"><strong>${state.sessions}</strong><span>Completed sessions</span></div><div class="stat"><strong>${independent}</strong><span>Answers on my own</span></div><div class="stat"><strong>${state.days.length}</strong><span>Days practised</span></div></div><div class="list">${(app==='words'?[{id:'words',title:'Word building'}]:topics).map(t=>{let p=state.skills[t.id]||{};return `<div class="list-item"><strong>${t.title}</strong><span class="muted">${p.independent||0} ${t.id==='words'?'built without hints':'independent'} · ${p.supported||0} with help · ${p.completed||0} sessions</span></div>`}).join('')}</div>${Object.keys(state.words).length?`<h2>Words to revisit</h2><div class="row">${Object.values(state.words).filter(w=>w.due<=Date.now()).map(w=>`<span class="word-chip">${esc(w.word)}</span>`).join('')||'<p class="muted">No words due yet. Revisit a journey whenever you like.</p>'}</div>`:''}${notice()}<p class="muted">These counts show practice, not a school grade or proof of mastery. Word discovery counts tile building; spelling counts recall without visible tiles. These are recorded separately within Spellbound.</p>`,'progress')}
function collection(){const choices=[['River',0,'A fresh start'],['Ocean',10,'Two sessions'],['Sunset',25,'Five sessions'],['Forest',50,'Ten sessions']];view(`<span class="eyebrow">Your collection</span><h1>Make this place yours.</h1><p class="muted">Earn five stars each time you finish a session, including sessions with hints.</p><div class="reward"><span class="pill">${state.stars} stars collected</span><h2>${state.theme} explorer</h2><p>Choose a colour theme for your adventure. Stars are collected, never spent.</p></div><div class="grid">${choices.map(([name,cost,desc])=>`<button class="theme-choice ${state.theme===name?'selected':''}" data-theme="${name}" ${state.stars<cost?'disabled':''}><h3>${name}</h3><p>${state.stars<cost?cost+' stars to unlock':state.theme===name?'Selected':'Choose theme'}</p><span class="muted">${desc}</span></button>`).join('')}</div>`,'collection');main.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;save();theme();collection()})}
function theme(){const themes={Ocean:['#126baf','#e8f3fb'],Sunset:['#ad481f','#fff0e7'],Forest:['#247443','#e8f5ee']};let t=themes[state.theme];if(t){document.body.style.setProperty('--accent',t[0]);document.body.style.setProperty('--soft',t[1])}else{document.body.style.removeProperty('--accent');document.body.style.removeProperty('--soft')}}
function grownups(){view(`<span class="eyebrow">For grown-ups</span><h1>Practice with a purpose.</h1><p>Activities offer support for selected Year 4 skills. They are not a complete curriculum, a formal assessment or an official Sounds-Write resource.</p><details open><summary>How learning and progress work</summary><p>Sessions are untimed. Hints and worked explanations remain available. Supported questions return once within the session. Spelling words are prioritised for later practice using a simple review schedule. Answers with and without help are recorded separately.</p><p>A session earns five stars and a practice day. Leaving early keeps completed answers but does not earn a completed session. Streaks count consecutive local calendar days. Missing a day resets the streak but never removes learning or rewards.</p><p>Saved progress stays in this browser on this device, separately for each game. Clearing browser data removes it. There are no accounts or cloud backups.</p></details><details><summary>Curriculum connections and remaining coverage</summary><p>Mappings refer to QCAA’s Australian Curriculum v9 Year 4 resources. A mapping means a skill is practised; it does not mean the whole content description has been covered.</p><div style="overflow:auto"><table><thead><tr><th>Journey</th><th>Curriculum connection</th></tr></thead><tbody>${(app==='words'?[{title:'Word building',code:'Vocabulary and spelling exploration; supplementary practice'}]:topics).map(t=>`<tr><td>${t.title}</td><td>${t.code}</td></tr>`).join('')}</tbody></table></div><p>Further maths work is needed on hands-on measurement, area estimation, creating shapes and symmetrical designs, student-created algorithms, and collecting and presenting survey data. Reading activities use short original passages; classroom study of complete texts, literature, speaking and listening remains essential.</p><p><a href="https://www.qcaa.qld.edu.au/downloads/aciqv9/mathematics/curriculum/ac9_maths_yr4_as_cd_alignment.pdf">QCAA Year 4 maths</a> · <a href="https://www.qcaa.qld.edu.au/downloads/aciqv9/english/curriculum/ac9_english_yr4_as_cd_alignment.pdf">QCAA Year 4 English</a></p></details><details><summary>Spelling approach</summary><p>Sound foundations use individual sounds, including separate consonants in words such as frog. Other journeys explicitly use syllable chunks or meaningful word parts. These are different supports. Spoken audio depends on the device’s available voice. Match practice words to school teaching where possible.</p></details><p><a href="classic.html">Open the original game</a></p>${notice()}`,'grownups')}
function writing(){view(`<section class="session"><span class="eyebrow">Story workshop</span><h1>A door appears in the school garden…</h1><p class="muted">Who finds it? What is on the other side? Write for a friend who loves a mystery.</p><article class="question"><label for="story"><strong>Your story</strong></label><textarea class="field" id="story" placeholder="Begin with a character, a place and something unexpected…">${esc(state.story)}</textarea><div class="feedback help">Build your story: introduce the character and setting, add a problem, then decide how it changes. Use a new paragraph when the scene or main idea changes.</div><h3>Read it back</h3><p><label><input type="checkbox" id="check-story"> I checked my paragraphs, sentence punctuation and any spellings I was unsure about.</label></p><div class="row"><button class="btn" id="save-story">Save draft</button><button class="btn secondary" id="finish-story">Finish writing practice</button></div><div class="feedback" id="feedback" role="status"></div></article></section>`);document.getElementById('story').oninput=e=>{state.story=e.target.value;save()};document.getElementById('save-story').onclick=()=>{save();feedback(saveAvailable?'Draft saved on this device.':'Saving is unavailable. Copy your story somewhere safe.','help')};document.getElementById('finish-story').onclick=()=>{if(state.story.trim().split(/\s+/).length<20||!document.getElementById('check-story').checked){feedback('Write at least 20 words, then read it back and tick the check.','help');return}session={topic:topics.find(t=>t.id==='writing'),independent:0,supported:0};finish()}}
const WordRacks=[['Riverbank','PAINT'],['Garden path','STARE'],['Woodland','BLAND'],['Island','PLANETS'],['Creek','BREAKIN'],['Lookout','STRANGLED']];
let rack=[],used=[],built=[],found=[],wordHelped=false,wordAwarded=false,wordHint='';
function canBuild(word,letters){let rest=[...letters.join('').toLowerCase()];return [...word].every(c=>{let i=rest.indexOf(c);if(i<0)return false;rest.splice(i,1);return true})}
function wordHome(){dailyActive=false;view(`<section class="hero"><div class="welcome"><span class="eyebrow">Word discovery · Year 4</span><h1>A little word adventure.</h1><p class="muted">Find words hiding in a handful of letters. Take your time, follow a clue and discover something new.</p></div><aside class="today"><span class="eyebrow">Practice streak</span><p><strong>${streak()} days</strong></p><span>Find five words to complete a session.</span></aside></section><div class="section-title"><h2>Pick a place to explore</h2><span class="pill">No timer</span></div><div class="grid">${WordRacks.map(([name,letters],i)=>`<button class="card" data-rack="${i}"><span class="symbol">${i+1}</span><h3>${name}</h3><p>${letters.length} letters · ${letters.split('').join(' · ')}</p><div class="foot"><span>Find five words</span><span>Explore →</span></div></button>`).join('')}</div>${notice()}<button class="btn quiet" id="adventure-back" onclick="home()">Back to my adventure</button>`);main.querySelectorAll('[data-rack]').forEach(b=>b.onclick=()=>{rack=WordRacks[Number(b.dataset.rack)][1].split('');found=[];used=[];built=[];wordAwarded=false;wordHelped=false;wordHint='';wordPlay()})}
function wordPlay(){view(`<section class="session"><div class="session-head"><button class="btn quiet" id="leave">Leave session</button><span class="pill">${found.length} / ${wordGoal()} words</span></div><article class="question"><span class="eyebrow">Capy’s word search</span><h1>What can you make?</h1><p class="muted">${dailyActive?'Look for '+esc(state.mission.anchor)+', then discover two more words.':'Use each tile once per word. Find words with two or more letters.'}</p><div class="word-built" aria-live="polite">${built.join('')||'…'}</div><div class="tiles">${rack.map((l,i)=>`<button class="tile" data-tile="${i}" aria-label="Letter ${l}" ${used.includes(i)?'disabled':''}>${l}</button>`).join('')}</div><div class="row"><button class="btn" id="check-word">Check word</button><button class="btn quiet" id="back">Backspace</button><button class="btn secondary" id="word-hint">Give me a clue</button></div><div class="feedback ${wordHint?'help':''}" id="feedback" role="status">${esc(wordHint)}</div><div class="row" style="margin-top:20px">${found.map(w=>`<span class="word-chip">${esc(w)}</span>`).join('')}</div></article></section>`);document.getElementById('leave').onclick=()=>{checkpointDiscovery();home()};main.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{let i=Number(b.dataset.tile);used.push(i);built.push(rack[i]);wordPlay()});document.getElementById('back').onclick=()=>{used.pop();built.pop();wordPlay()};document.getElementById('check-word').onclick=checkWord;document.getElementById('word-hint').onclick=()=>{let possible=WordDictionary.filter(w=>canBuild(w,rack)&&!found.includes(w));let w=possible.sort((a,b)=>a.length-b.length)[0];wordHelped=true;wordHint=w?`Try a ${w.length}-letter word beginning with “${w[0]}”. ${WordClues[w]||'Rearrange the letters and say the word aloud.'}`:'You found all the words in this collection.';feedback(wordHint,'help')}}
function checkWord(){let w=built.join('').toLowerCase();if(found.includes(w)){feedback('You already found that one. Try a different word.','help');return}if(!canBuild(w,rack)||!WordDictionary.includes(w)){wordHelped=true;feedback('That spelling is not in this game’s word collection. It may still be a word. Try another, or ask a grown-up.','warn');return}found.push(w);let p=state.skills.words||(state.skills.words={independent:0,supported:0,completed:0});p[wordHelped?'supported':'independent']++;save();built=[];used=[];wordHelped=false;wordHint='';if(found.length>=wordGoal()&&(!dailyActive||found.includes(state.mission.anchor))&&!wordAwarded){wordAwarded=true;p.completed++;if(dailyActive){finishDailyDiscovery();return}complete();view(`<section class="session"><span class="eyebrow">Word adventure complete</span><h1>Five discoveries. Nicely done.</h1><div class="row">${found.map(w=>`<span class="word-chip">${esc(w)}</span>`).join('')}</div><div class="reward"><h2>+5 stars</h2><p>Your discoveries are saved in your word pocket. Try using one in a story.</p></div><button class="btn" id="return">Explore another place</button></section>`);document.getElementById('return').onclick=()=>{dailyActive=false;wordHome()}}else{wordPlay();feedback(`Found it: ${w}. ${WordClues[w]||'Say it aloud and think of a sentence that uses it.'}`)}}
document.querySelector('.brand').onclick=home;
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>({play:home,progress,collection,grownups}[b.dataset.nav])());
document.addEventListener('keydown',e=>{if(!document.getElementById('check-word')||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Enter'&&e.target.tagName!=='BUTTON'){e.preventDefault();checkWord()}else if(e.key==='Backspace'){e.preventDefault();used.pop();built.pop();wordPlay()}else if(/^[a-z]$/i.test(e.key)){let i=rack.findIndex((l,i)=>l===e.key.toUpperCase()&&!used.includes(i));if(i>=0){used.push(i);built.push(rack[i]);wordPlay()}}});
/* adventure.js boots the combined experience after these shared activities are ready. */
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
