/* Original practice activities mapped to selected Australian Curriculum v9 Year 4 descriptions.
   Curriculum mappings indicate practice opportunities, not complete assessment coverage. */
const MathsTopics=[
 ['fractions','Fraction studio','½','Equal parts, matching fractions and decimals.','AC9M4N03, AC9M4N01'],
 ['numberline','Fraction trails','↔','Count in fractions, including beyond one whole.','AC9M4N04'],
 ['area','Area workshop','▦','Cover shapes with square units. Find the space inside.','AC9M4M02'],
 ['perimeter','Perimeter paths','□','Measure the distance around a shape.','AC9M4M02'],
 ['facts','Multiplication & division','×','Build facts from groups and facts you already know.','AC9M4A02'],
 ['numbers','Number lab','10','Place value, decimals, odd and even numbers.','AC9M4N01, AC9M4N02, AC9M4N05'],
 ['problems','Everyday problems','$','Work with money and make a good guess before you count.','AC9M4N06, AC9M4N07, AC9M4N08'],
 ['patterns','Pattern detective','?','Missing numbers and rules that keep going.','AC9M4A01, AC9M4N09'],
 ['measure','Measure & time','◷','Read scales and work out how long things take.','AC9M4M01, AC9M4M03'],
 ['space','Shape explorer','△','Angles, symmetry, shapes and grid references.','AC9M4M04, AC9M4SP01–03'],
 ['data','Data detective','▥','Read displays and think about what they tell us.','AC9M4ST01, AC9M4ST02'],
 ['chance','Chance lab','◇','Compare chances and explore repeated experiments.','AC9M4P01, AC9M4P02']
].map(([id,title,icon,desc,code])=>({id,title,icon,desc,code}));
const pick=a=>a[Math.floor(Math.random()*a.length)];
const int=(a,b)=>a+Math.floor(Math.random()*(b-a+1));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=int(0,i);[a[i],a[j]]=[a[j],a[i]]}return a};
function q(prompt,answer,others,hint,explain,visual=''){return {prompt,answer:String(answer),choices:shuffle([...new Set([answer,...others].map(String))]),hint,explain,visual}}
function blocks(rows,cols,count=rows*cols){return `<div class="squares" style="grid-template-columns:repeat(${cols},30px)" role="img" aria-label="${count} unit squares arranged in rows">${Array.from({length:rows*cols},(_,i)=>`<span class="square ${i>=count?'empty':''}"></span>`).join('')}</div>`}
function bar(n,d){return `<div class="fraction" role="img" aria-label="${n} of ${d} equal parts shaded">${Array.from({length:d},(_,i)=>`<i class="${i<n?'filled':''}"></i>`).join('')}</div><div class="caption">One whole, divided into ${d} equal parts</div>`}
function makeMath(id,index=0){let a=int(2,9),b=int(2,9),v=index%3;
 switch(id){
 case 'fractions':if(v===0){let d=pick([4,6,8,10]),n=d/2;return q(`Which fraction names the shaded amount?`,`${n}/${d}`,[`1/${d}`,`${n-1}/${d}`,`${d}/${n}`],'The bottom number counts every equal part. The top number counts shaded parts.',`${n} of ${d} equal parts are shaded. ${n}/${d} is also one half.`,bar(n,d))}if(v===1){let d=pick([2,3,4]),n=int(1,d-1);return q(`${n}/${d} = ?/${d*2}`,n*2,[n,n*2+1,d*2],'Split each part in two. How many shaded parts are there now?',`Multiply both numbers by 2: ${n}/${d} = ${n*2}/${d*2}. The amount stays the same.`,bar(n,d))}let n=int(1,9);return q(`Write ${n}/10 as a decimal.`,(n/10).toFixed(1),[`${n}.0`,`0.0${n}`,`${n}.10`],'The first place after the decimal point is tenths.',`${n}/10 means ${n} tenths, written 0.${n}.`,bar(n,10));
 case 'numberline':{let d=pick([2,4]),n=int(d+1,d*2-1),ans=`${Math.floor(n/d)} ${n%d}/${d}`;return q(`Which number shows the whole and the fraction at the dot?`,ans,[`1 ${d-n%d}/${d+1}`,`${n}/${d+1}`,`${n%d}/${d}`],`Each step is 1/${d}. Count ${d} steps to reach one whole, then keep counting.`,`${n}/${d} is ${ans}: one whole and ${n%d} more ${d===2?'half':'quarters'}.`,`<div class="numberline">${Array.from({length:d*2+1},(_,i)=>`<span class="${i===n?'marked':''}">${i===n?'● ?':i===0?'0':i===d?'1':i===d*2?'2':'│'}</span>`).join('')}</div><div class="caption">Equal steps of 1/${d}</div>`)}
 case 'area':{let r=int(2,5),c=int(3,7),total=v===1?r*c-2:r*c;return q(v===2?'Each small square has an area of 1 cm². What is the area in cm²?':'How many square units cover this shape?',total,[total+2,total-1,2*(r+c)],'Count the squares inside the shape. Count full rows first, then any extra squares.',v===1?`${r-1} full rows of ${c}, then ${c-2} squares: ${total} square units.`:`${r} rows of ${c} squares cover ${total} square units. Area measures the inside.`,blocks(r,c,total)+`<div class="caption">Each small square = ${v===2?'1 cm²':'1 square unit'}</div>`)}
 case 'perimeter':return q(`A rectangle is ${a} cm long and ${b} cm wide. What is its perimeter in cm?`,2*(a+b),[a*b,a+b,2*a+b],'Trace all four sides: length, width, length, width.',`${a} + ${b} + ${a} + ${b} = ${2*(a+b)} cm. Perimeter measures the boundary.`,blocks(2,4)+`<div class="caption">Rectangle: ${a} cm by ${b} cm (diagram not to scale)</div>`);
 case 'facts':if(v===1)return q(`${a*b} ÷ ${a} = ?`,b,[b+1,b-1,a*b],'Think of the related multiplication: how many groups of '+a+' make '+a*b+'?',`${a} × ${b} = ${a*b}, so ${a*b} ÷ ${a} = ${b}.`);return q(`${a} × ${b} = ?`,a*b,[a*b+b,a*b-b,a+b],a>5?`Start with 5 × ${b}. Then add ${a-5} more groups of ${b}.`:`Build ${a} equal groups with ${b} in each group.`,a>5?`5 × ${b} = ${5*b}. Add ${(a-5)*b} to get ${a*b}.`:`${a} groups of ${b} make ${a*b}.`,blocks(a,b));
 case 'numbers':if(v===0)return q(`What is the value of the ${a} in 3.${a}${b}?`,`${a} tenths`,[`${a} hundredths`,`${a} tens`,`${a} ones`],'The first digit after the decimal point counts tenths.',`In 3.${a}${b}, the ${a} is in the tenths place.`);if(v===1)return q(`${a*10} × ${b} = ?`,a*10*b,[a*b,a*10+b,a*100*b],`Use ${a} × ${b}, then make the result ten times as large.`,`${a} × ${b} = ${a*b}. ${a*10} × ${b} = ${a*b*10}.`);return q('An odd number plus an odd number is always…','even',['odd','zero','a multiple of 10'],'Pair up objects for each number. Each odd group has one left over.','The two leftover objects form another pair, making an even total.');
 case 'problems':if(v===0)return q(`You buy ${a} notebooks at $${b} each. How much do you spend?`,`$${a*b}`,[`$${a+b}`,`$${a*b+b}`,`$${a*b-b}`],'This is equal groups: number of notebooks × price of each.',`${a} × $${b} = $${a*b} altogether.`);if(v===1)return q(`You have $${a*10}. You spend $${b}. How much is left?`,`$${a*10-b}`,[`$${a*10+b}`,`$${a*10-b-1}`,`$${a-b}`],'Subtract the cost from the amount you started with.',`$${a*10} − $${b} = $${a*10-b}.`);return q('Estimate $48 + $31 by rounding each amount to the nearest $10.','$80',['$70','$90','$79'],'48 is closer to 50 than 40. What is 31 closest to?', '$50 + $30 = $80. The exact total, $79, is close to this estimate.');
 case 'patterns':if(v===0)return q(`${a*10} + ? = ${a*10+b}`,b,[b+1,a,a*10+b],'Use subtraction to undo the addition.',`${a*10+b} − ${a*10} = ${b}.`);if(v===1)return q(`Start at ${a}. Add ${b} each time: ${a}, ${a+b}, ${a+2*b}, ?`,a+3*b,[a+2*b+1,a+4*b,a+2*b-1],`Apply the same “add ${b}” instruction again.`,`${a+2*b} + ${b} = ${a+3*b}.`);return q(`${a*10} − ? = ${a*10-b}`,b,[b+2,a*10+b,a],'Find the difference between the starting and ending numbers.',`${a*10} − ${a*10-b} = ${b}.`);
 case 'measure':if(v===0)return q(`A lesson starts at ${a}:20 am and lasts 50 minutes. When does it finish?`,`${a+1}:10 am`,[`${a}:70 am`,`${a+1}:20 am`,`${a}:50 am`],'First count 40 minutes to the next hour. Then add the remaining 10 minutes.',`40 minutes reaches ${a+1}:00 am. Another 10 minutes reaches ${a+1}:10 am.`);if(v===1)return q(`${a} hours and 15 minutes is how many minutes?`,a*60+15,[a*100+15,a*60,a*60+30],'Each hour contains 60 minutes.',`${a} × 60 + 15 = ${a*60+15} minutes.`);return q('A jug scale is marked 200 mL and 400 mL. The water is halfway between. How much water is there?','300 mL',['250 mL','600 mL','200 mL'],'Find half of the gap between the two marks.','The gap is 200 mL. Half is 100 mL, so 200 + 100 = 300 mL.');
 case 'space':if(v===0)return q('An angle is larger than a right angle but smaller than a straight angle. What is it called?','obtuse',['acute','reflex','revolution'],'A right angle is a square corner. A straight angle is a half turn.','An obtuse angle is wider than a square corner but smaller than a straight line.');if(v===1)return q('On a grid, columns run A, B, C, D from left to right. Rows increase upwards. Start at B2. Move one column right, then one row up. Where are you?','C3',['A3','C1','B3'],'Change the column letter for right, then increase the row number for up.','B → C and 2 → 3, so the destination is C3.');return q('How many lines of symmetry does a square have?',4,[1,2,3],'Try a vertical fold, a horizontal fold and the diagonal folds.','A square matches across four lines: vertical, horizontal and both diagonals.');
 case 'data':if(v===0)return q('In this picture graph, each dot stands for 4 votes. A choice has 3 symbols. How many votes is that?',12,[3,7,4],'Use the key: count four votes for every symbol.','3 × 4 = 12 votes. Always check the key.','<div class="caption" style="font-size:30px">● ● ●</div><div class="caption">Key: ● = 4 votes</div>');if(v===1)return q('A survey finds: cats 8 votes, dogs 12, birds 4. How many more votes did dogs get than cats?',4,[20,8,12],'“How many more” asks for the difference.','12 − 8 = 4 more votes for dogs.');return q('You want to compare how many children chose each favourite fruit. Which way of showing the results helps most?','A labelled column graph',['An unlabelled list of names','A clock face','A number line with no labels'],'Choose a display that makes category totals easy to compare.','A labelled column graph lets you compare totals using the heights of columns.');
 case 'chance':if(v===0)return q('A bag has 6 blue counters and 2 yellow counters. Which colour are you more likely to pick?','blue',['yellow','both equally likely','neither is possible'],'Compare how many counters there are of each colour.','There are more blue counters, so blue is more likely. Yellow is still possible.');if(v===1)return q('You toss a fair coin and get heads. What is true about the next toss?','Heads and tails are equally likely',['Tails must happen next','Heads must happen next','Heads is now impossible'],'Each toss is a fresh start. The last toss does not change it.','A fair coin does not remember the previous toss. Both outcomes remain equally likely.');return q('Two people each toss a fair coin 10 times. Must they get the same number of heads?','No, results can vary',['Yes, exactly 5 each','Yes, exactly 10 each','Only if they toss slowly'],'A fair coin can still give more heads than tails in a few tosses.','Repeated chance experiments can produce different results, even with the same fair coin.');
 }
}
const SpellingTopics=[
 ['sounds','Sound foundations','sh','Hear sounds and connect them with spellings.','Foundation revision'],
 ['vowels','Vowel spellings','ai','Explore different ways to spell familiar sounds.','AC9E4LY09'],
 ['parts','Word parts','+','Add word beginnings and endings, like un- and -ful.','AC9E4LY09, AC9E4LY10'],
 ['longer','Longer words','abc','Break longer words into smaller parts.','AC9E4LY09'],
 ['homophones','Words in context','“ ”','Choose the spelling that fits the meaning.','AC9E4LY11'],
 ['sentences','Sentence studio','Aa','Join ideas and use marks that show someone is speaking.','AC9E4LA06, AC9E4LA09, AC9E4LA12'],
 ['reading','Reading detective','≋','Use clues to work out meaning and learn new words.','AC9E4LY05, AC9E4LA11'],
 ['writing','Story workshop','✎','Write a story, then read it back and improve it.','AC9E4LE05, AC9E4LY06']
].map(([id,title,icon,desc,code])=>({id,title,icon,desc,code}));
const SpellWords={
 sounds:[['ship','sh|i|p','The ship sailed home.'],['frog','f|r|o|g','The frog jumped.'],['band','b|a|n|d','The band played.'],['milk','m|i|l|k','I poured the milk.'],['crust','c|r|u|s|t','The bread has a crust.'],['blend','b|l|e|n|d','Blend the colours.'],['stomp','s|t|o|m|p','Stomp your feet.'],['wish','w|i|sh','Make a wish.']],
 vowels:[['rain','r|ai|n','The rain fell.'],['boat','b|oa|t','We rowed the boat.'],['night','n|igh|t','The stars shine at night.'],['seed','s|ee|d','Plant a seed.'],['shout','sh|ou|t','Please do not shout.'],['coin','c|oi|n','I found a coin.'],['snail','s|n|ai|l','A snail crossed the path.'],['feet','f|ee|t','My feet are wet.']],
 parts:[['unhappy','un|happy','The ending made her unhappy.'],['helpful','help|ful','Thank you for being helpful.'],['careless','care|less','A careless step spilled the paint.'],['replay','re|play','We can replay the song.'],['dislike','dis|like','I dislike cold soup.'],['hopeful','hope|ful','I am hopeful about tomorrow.'],['jumped','jump|ed','The frog jumped.'],['happiness','happy → happiness','The news brought happiness.']],
 longer:[['fantastic','fan|tas|tic','What a fantastic idea.'],['remember','re|mem|ber','Remember your hat.'],['different','dif|fer|ent','We chose different colours.'],['important','im|por|tant','Water is important.'],['animal','an|i|mal','Choose an animal.'],['together','to|geth|er','We worked together.'],['because','be|cause','I smiled because you came.'],['tomorrow','to|mor|row','We will visit tomorrow.']],
 homophones:[['their','their','Their dog has a red collar.'],['there','there','Put the bag over there.'],['they\'re','they\'re','They\'re going to the park.'],['hear','h|ear','I can hear the birds.'],['here','here','Please sit here.'],['piece','p|ie|ce','May I have a piece of cake?'],['peace','p|ea|ce','The quiet garden was full of peace.'],['right','r|igh|t','Turn right at the shop.'],['write','wr|i|t|e','Write your name.']]
};
function spellQuestion(topic,entry){let [word,parts,sentence]=entry;return {kind:'spell',word,parts:parts.split('|'),sentence,answer:word,prompt:topic==='homophones'?'Listen to the sentence. Spell the missing word.':'Listen, then spell the word.',hint:topic==='parts'?'Think about the base word and what the added part means.':topic==='longer'?'Say the word in small chunks. Spell one chunk at a time.':topic==='homophones'?'Think about what the sentence means. That helps you choose the spelling.':'Say the word slowly. Listen for each sound, then think about its spelling.',explain:topic==='parts'?`Notice the word parts: ${parts.replaceAll('|',' + ')}.`:`Read ${word}, cover it, then try it again later.`,id:topic+':'+word,topic}}
const EnglishQuestions={
 sentences:[q('Choose the word that connects a reason: “We stayed inside ___ it was raining.”','because',['although','before','unless'],'Which joining word tells us why?','“Because” introduces the reason for staying inside.'),q('Which sentence uses the past tense?','She walked home.',['She walks home.','She will walk home.','She is walking home.'],'Look for an action that has already happened.','“Walked” tells us the action happened in the past.'),q('Which sentence correctly shows someone speaking?','“Come here,” said Mia.',['Come here, said Mia.','“Come here, said Mia.”','come here said Mia'],'Put speech marks (“ ”) around just the words someone says.','Only “Come here” is spoken. Put the comma before the last speech mark.'),q('Which sentence joins the ideas clearly?','Although it was cold, we went swimming.',['Although it was cold.','We went swimming although.','Cold swimming we although.'],'Start with a full sentence. Add more detail using a word like “although”.','“We went swimming” is a full sentence. “Although it was cold” adds a surprising detail.'),q('Which sentence describes something that will happen?','We will paint tomorrow.',['We painted yesterday.','We paint every day.','We are painting now.'],'Look for a future action.','“Will paint” and “tomorrow” signal the future.'),q('Choose the action word that gives the clearest picture: “The mouse ___ into its hole.”','scurried',['went','did','was'],'Think about a small animal moving quickly.','“Scurried” helps the reader picture quick little movements.')],
 reading:[q('Mia packed a towel and goggles. She checked the pool opening time. Where is she probably going?','Swimming',['To the library','To a concert','To buy shoes'],'Use more than one clue in the text.','The towel, goggles and pool opening time all support swimming.'),q('“The path was silent. Leo stopped when a twig snapped behind him.” How does this part make the reader feel?','Suspense',['Celebration','Boredom','Relief'],'Notice the sudden sound and Leo stopping.','The unexpected sound makes us wonder what is behind Leo.'),q('“The exhausted runner sat down.” Which word is closest in meaning to exhausted?','Very tired',['Very hungry','Excited','Confused'],'Use the runner sitting down as a clue.','“Exhausted” means very tired.'),q('“First we planted seeds. Later, green shoots appeared.” What does “Later” tell us?','Time has passed',['A reason','A place','An opinion'],'Think about how the two events are ordered.','“Later” links the events in time.'),q('A poster says, “Join our clean-up! Help protect the creek.” What is its main purpose?','Persuade people to help',['Tell a fantasy story','List every creek','Explain multiplication'],'Look at what the poster asks the reader to do.','The poster asks people to help and tells them why.'),q('“The puppy hid under the chair during the thunder.” What can you work out from these clues?','The puppy may be frightened',['The puppy can fly','The puppy loves loud noise','The chair is outside'],'Use clues to make a good guess. The text may not tell you for sure.','Hiding during thunder suggests fear, although the text does not say it directly.')]
};
