/* Show real saved practice. Earlier sessions have no per-day counts: never invent them. */
state.practiceLog = state.practiceLog && typeof state.practiceLog==='object' ? state.practiceLog : {};
const progressComplete=complete;
complete=function(){progressComplete();const d=day();state.practiceLog[d]=(state.practiceLog[d]||0)+1;save()};
progress=function(){
  const recent=Array.from({length:14},(_,i)=>{const d=new Date();d.setDate(d.getDate()-13+i);return {key:day(d),label:d.toLocaleDateString('en-AU',{day:'numeric',month:'short'}),short:d.toLocaleDateString('en-AU',{weekday:'short'})}});
  const sessions=recent.map(d=>Number(state.practiceLog[d.key])||0),max=Math.max(1,...sessions);
  const totalLogged=sessions.reduce((a,b)=>a+b,0);
  const rows=topics.filter(t=>t.id!=='writing').map(t=>({ ...t,p:state.skills[t.id]||{independent:0,supported:0}}));
  const scale=Math.max(1,...rows.map(t=>(t.p.independent||0)+(t.p.supported||0)));
  const own=rows.filter(t=>t.id!=='words').reduce((n,t)=>n+(t.p.independent||0),0);
  const milestone=[5,10,20,40,75,100].find(n=>n>state.sessions)||Math.ceil((state.sessions+1)/25)*25;
  view(`<section class="progress-heading"><div><span class="eyebrow">Every little step counts</span><h1>Look what you’ve done!</h1><p class="muted">See what you’ve tried and choose what to practise next.</p></div><span class="progress-medal" aria-hidden="true">✦</span></section>
    <div class="stats"><div class="stat"><strong>${state.sessions}</strong><span>Sessions finished</span></div><div class="stat"><strong>${state.days.length}</strong><span>Days I practised</span></div><div class="stat"><strong>${own}</strong><span>Answers on my own</span></div></div>
    <section class="progress-panel milestone"><div><h2>Next stop: ${milestone} sessions</h2><p>${milestone-state.sessions} more to go. Hints count as learning too.</p></div><div class="milestone-track" role="progressbar" aria-label="Sessions towards next milestone" aria-valuemin="0" aria-valuemax="${milestone}" aria-valuenow="${state.sessions}"><span style="width:${Math.min(100,state.sessions/milestone*100)}%"></span></div></section>
    <section class="progress-panel"><h2>My last two weeks</h2><p class="muted">${totalLogged?`${totalLogged} sessions shown below.`:'Finish a session to start your chart.'} This chart counts sessions from this update onwards.</p><div class="session-chart" tabindex="0" role="img" aria-label="Sessions over the last fourteen days: ${recent.map((d,i)=>`${d.label}: ${sessions[i]}`).join('; ')}">${recent.map((d,i)=>`<div class="chart-column"><strong>${sessions[i]}</strong><div class="bar-track"><span style="height:${sessions[i]/max*100}%"></span></div><span>${d.key.slice(8)}/${Number(d.key.slice(5,7))}</span></div>`).join('')}</div>
    <h3>Days I showed up</h3><div class="practice-days" tabindex="0" aria-label="Days practised in the last two weeks">${recent.map(d=>`<div class="practice-day ${state.days.includes(d.key)?'practised':''}"><span>${d.short}</span><strong>${state.days.includes(d.key)?'✓':'·'}</strong><small>${d.label}</small></div>`).join('')}</div><p class="muted">A gap is OK. Your words, stars and finished work stay yours.</p></section>
    <section class="progress-panel"><h2>What I’ve been practising</h2><p class="muted">Each bar counts answers, including another try at the same question. Longer bars mean more practice.</p><div class="chart-key"><span><i></i>On my own</span><span><i class="help-colour"></i>With help</span></div><div class="skill-chart">${rows.map(t=>{let a=t.p.independent||0,b=t.p.supported||0;return `<div class="skill-chart-row"><button class="skill-jump" data-practise="${t.id}">${t.title} <span>→</span></button><div class="skill-bar" role="img" aria-label="${t.title}: ${a} ${t.id==='words'?'words built without hints':'answers on my own'}, ${b} with help"><span style="width:${a/scale*100}%"></span><span class="help-colour" style="width:${b/scale*100}%"></span></div><span class="skill-total">${a} + ${b}</span></div>`}).join('')}</div><p class="muted">${app==='spelling'?'Word discovery counts words built with tiles. It is separate from spelling a word from memory.':'Stage designs use help from the model, so they are separate from answers on your own.'} These charts show practice, not a school mark.</p></section>${app==='maths'?`<p class="pill">Design workshops finished: ${state.gardens||0}</p>`:''}${notice()}`,'progress');
  main.querySelectorAll('[data-practise]').forEach(b=>b.onclick=()=>start(b.dataset.practise));
};
